stateDiagram-v2
    direction TB

    [*] --> IniciarConfiguracao
    
    IniciarConfiguracao : Receber dados da Regra de Filtragem
    IniciarConfiguracao --> IdentificarSubclasse

    IdentificarSubclasse : Identificar Subclasse do Solicitante(Quem está logado)
    IdentificarSubclasse --> SubclasseSolicitante

    state SubclasseSolicitante <<choice>>
    
    SubclasseSolicitante --> AnalistaDeSOC : AnalistaDeSOC
    SubclasseSolicitante --> LiderDeSOC : LiderDeSOC
    SubclasseSolicitante --> AdministradorDoSistema : AdministradorDoSistema

    AnalistaDeSOC --> RetornarErroPermissao
    LiderDeSOC --> RetornarErroPermissao
    RetornarErroPermissao : Retornar Erro: Acesso Negado.Apenas Administradores configuram regras.

    AdministradorDoSistema --> ValidarDadosRegra
    
    ValidarDadosRegra : Validar parâmetros da Regra (Severidade, Origem, Padrão)
    ValidarDadosRegra --> DadosValidos

    state DadosValidos <<choice>>
    
    DadosValidos --> RetornarErroValidacao : Inválidos
    RetornarErroValidacao : Retornar Erro:Dados incorretos ou incompletos
    
    DadosValidos --> SalvarRegra : Válidos
    SalvarRegra : Salvar Regra de Filtragem\nna base de dados
    
    SalvarRegra --> PersistirTrilha
    PersistirTrilha : Persistir Trilha de Auditoria no RegistroDeHistorico
    
    PersistirTrilha --> RetornarSucesso
    RetornarSucesso : Retornar Mensagem de Sucesso

    RetornarErroPermissao --> Fim
    RetornarErroValidacao --> Fim
    RetornarSucesso --> Fim
    
    Fim --> [*]