stateDiagram-v2
    direction TB

    [*] --> IniciarExportacao
    
    IniciarExportacao : Solicitar exportacao de relatorio
    IniciarExportacao --> IdentificarSubclasse

    IdentificarSubclasse : Identificar Subclasse do Solicitante
    IdentificarSubclasse --> SubclasseSolicitante

    state SubclasseSolicitante <<choice>>
    
    SubclasseSolicitante --> AnalistaDeSOC : AnalistaDeSOC
    SubclasseSolicitante --> LiderDeSOC : LiderDeSOC
    SubclasseSolicitante --> AdministradorDoSistema : AdministradorDoSistema

    AnalistaDeSOC --> RetornarErroPermissao
    RetornarErroPermissao : Retornar Erro Acesso Negado Apenas Lideres e Administradores podem exportar relatorios

    LiderDeSOC --> SelecionarFormato
    AdministradorDoSistema --> SelecionarFormato
    
    SelecionarFormato : Selecionar formato de exportacao
    SelecionarFormato --> BuscarDados
    
    BuscarDados : Buscar dados consolidados do relatorio
    BuscarDados --> DadosExistem

    state DadosExistem <<choice>>
    
    DadosExistem --> RetornarErroVazio : Nao
    RetornarErroVazio : Retornar Erro Nao ha dados para exportar
    
    DadosExistem --> GerarArquivoFisico : Sim
    GerarArquivoFisico : Gerar arquivo fisico do relatorio
    GerarArquivoFisico --> RetornarSucesso
    
    RetornarSucesso : Retornar arquivo para download e Mensagem de Sucesso

    RetornarErroPermissao --> Fim
    RetornarErroVazio --> Fim
    RetornarSucesso --> Fim
    
    Fim --> [*]