stateDiagram-v2
    direction TB

    [*] --> IniciarVisualizacao
    
    IniciarVisualizacao : Solicitar visualizacao de relatorios
    IniciarVisualizacao --> IdentificarSubclasse

    IdentificarSubclasse : Identificar Subclasse do Solicitante
    IdentificarSubclasse --> SubclasseSolicitante

    state SubclasseSolicitante <<choice>>
    
    SubclasseSolicitante --> AnalistaDeSOC : AnalistaDeSOC
    SubclasseSolicitante --> LiderDeSOC : LiderDeSOC
    SubclasseSolicitante --> AdministradorDoSistema : AdministradorDoSistema

    AnalistaDeSOC --> RetornarErroPermissao
    RetornarErroPermissao : Retornar Erro Acesso Negado Apenas Lideres e Administradores podem visualizar relatorios

    LiderDeSOC --> DefinirFiltros
    AdministradorDoSistema --> DefinirFiltros
    
    DefinirFiltros : Definir parametros de filtro dataInicial e dataFinal
    DefinirFiltros --> ConsultarBanco
    
    ConsultarBanco : Buscar relatorios consolidados na base de dados
    ConsultarBanco --> ExistemRelatorios

    state ExistemRelatorios <<choice>>
    
    ExistemRelatorios --> RetornarRelatorioVazio : Nao
    RetornarRelatorioVazio : Retornar Aviso Nenhum relatorio encontrado para o periodo selecionado
    
    ExistemRelatorios --> ExibirRelatorios : Sim
    ExibirRelatorios : Renderizar e exibir painel de relatorios
    
    RetornarErroPermissao --> Fim
    RetornarRelatorioVazio --> Fim
    ExibirRelatorios --> Fim
    
    Fim --> [*]